[package]
edition = "2021"
name = "learnopengl"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
cocoa = "0.24.0"
gl = "0.14.0"
glutin = "0.28.0"
image = {version = "0.24.1", default_features = false, features = ["jpeg", "png"]}
